build-MultimonNgLambdaLayer:
	mkdir -p "$(ARTIFACTS_DIR)/bin"
	curl --fail https://media.prx.org/tech/bin-multimon-ng/1.4.1/multimon-ng --output "$(ARTIFACTS_DIR)/bin/multimon-ng"
	chmod +x "$(ARTIFACTS_DIR)/bin/multimon-ng"
