build-MpckLambdaLayer:
	# TODO Build this layer, rather than copy a static asset
	curl https://media.prx.org/tech/bin-mpck.zip --output "$(ARTIFACTS_DIR)/bin-mpck.zip"
	unzip "$(ARTIFACTS_DIR)/bin-mpck.zip" -d "$(ARTIFACTS_DIR)"
	rm "$(ARTIFACTS_DIR)/bin-mpck.zip"
