extends: [airbnb-base, plugin:prettier/recommended]
plugins: [prettier, jest]
env:
  node: true
  es2023: true
parserOptions:
  ecmaVersion: 2023
  sourceType: module
rules:
  no-console: off
  no-param-reassign: off
  import/prefer-default-export: off
  import/extensions: off
overrides:
  - files:
      - src/lambdas/**/*.js
      - lib/**/*.js
    rules:
      import/no-extraneous-dependencies:
        - error
        - packageDir: "./"
  - files:
      - "**/*.test.js"
    env:
      jest/globals: true
