singleQuote: true
overrides:
  - files: "*.asl.json"
    options:
      parser: json
  - files: "*.md"
    options:
      tabWidth: 4
  - files: "Makefile"
    options:
      tabWidth: 4
      useTabs: true
  - files: "*.yml"
    options:
      singleQuote: false
      printWidth: 250
