Layout/LineLength:
  Enabled: false
Layout/FirstArgumentIndentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 150
Metrics/MethodLength:
  Max: 30
Style/GuardClause:
  Enabled: false
