# Porter does not currently have a CI build. This buildspec is run as part of
# the CodePipeline that deploys Porter via CloudFormation. It runs as an
# acceptance test step between staging and production deploys.
version: 0.2
env:
  variables:
    PRX_ECR_REGION: "us-east-1"
  parameter-store:
    PORTER_STATE_MACHINE_ARN: "/prx/stag/meta.prx.org/PORTER_STATE_MACHINE_ARN"
    PORTER_TEST_BUCKET_NAME: "/prx/stag/meta.prx.org/PORTER_TEST_BUCKET_NAME"
phases:
  install:
    runtime-versions:
      # This Ruby version does NOT need to match the version used in containers
      # like FTP or Transcode. It should be whatever is best for executing this
      # buildspec, such as performing acceptance tests.
      #
      # Available runtime versions are based on those offered by the image
      # being used by the CodeBuild project
      # https://github.com/PRX/Infrastructure/blob/main/devops/porter-cd-pipeline.yml#L492
      # https://docs.aws.amazon.com/codebuild/latest/userguide/runtime-versions.html
      ruby: 3.4
      nodejs: 22
  pre_build:
    commands:
      - make bootstrap
  build:
    commands:
      - make minitest
