version: '3.7'
networks:
  porternetwork:
    driver: bridge
    name: porternetwork
services:
  ci:
    build:
      context: ./
      dockerfile: ci.Dockerfile
    command: test
    # depends_on:
    #   - sam
    #   - step_functions
    # links:
    #   - step_functions
    networks:
      - porternetwork
    volumes:
      - .:/app
