version: "3.7"
networks:
  porternetwork:
    driver: bridge
    name: porternetwork
services:
  ci:
    build:
      context: ./
      dockerfile: ci.Dockerfile
    command: ["-k", "ci"]
    environment:
      - AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
      - PORTER_STATE_MACHINE_ARN
      - PORTER_TEST_BUCKET_NAME
    networks:
      - porternetwork
    # volumes:
    #   - .:/app
