version: '3.7'
networks:
  porternetwork:
    driver: bridge
    name: porternetwork
services:
  ci:
    build:
      context: ./
      dockerfile: ci.Dockerfile
    command: test
    networks:
      - porternetwork
    volumes:
      - .:/app
  sam:
    build:
      context: ./
      dockerfile: sam.Dockerfile
    command: ['$PWD']
    networks:
      - porternetwork
    ports:
      - '3001:3001'
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
  step_functions:
    build:
      context: ./
      dockerfile: step-functions.Dockerfile
    networks:
      - porternetwork
    ports:
      - '8083:8083'
    volumes:
      - .:/app
