version: "3.7"
services:
  step_functions:
    build: ./test/step-functions
  lambdas:
    build:
      context: ./
      dockerfile: ./test/lambdas/Dockerfile
  containers:
    build: ./test/containers
