version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "porter-example"
s3_bucket = "tktktktk" # This bucket has usually created by SAM previously
s3_prefix = "porter-example"
region = "us-east-1"
profile = "tktktktk"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TranscodeJobNamePrefix=\"porter-example-\" EnvironmentType=\"Staging\" OpsWarnMessagesSnsTopicArn=\"arn:…\" OpsErrorMessagesSnsTopicArn=\"arn:…\" TranscodeEcsTaskDefinitionImage=\"…\" FtpCopyEcsTaskDefinitionImage=\"…\""
