build-SoxLambdaLayer:
	mkdir -p "$(ARTIFACTS_DIR)/bin"
	curl https://raw.githubusercontent.com/serverlesspub/sox-aws-lambda-binary/master/vendor/bin/sox --output "$(ARTIFACTS_DIR)/bin/sox"
	chmod +x "$(ARTIFACTS_DIR)/bin/sox"
