build-PorterUtilLambdaLayer:
	mkdir -p "$(ARTIFACTS_DIR)/nodejs/node_modules/porter-util"
	cp index.js "$(ARTIFACTS_DIR)/nodejs/node_modules/porter-util"
	cp package.json "$(ARTIFACTS_DIR)/nodejs/node_modules/porter-util"
