# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "aws-sdk-s3", "~> 1"
gem "aws-sdk-cloudwatch", "~> 1"
gem "net-sftp"
