build-FileTypeLambdaLayer:
	mkdir -p "$(ARTIFACTS_DIR)/nodejs"
	npm install --prefix "$(ARTIFACTS_DIR)/nodejs" file-type
	npm install --prefix "$(ARTIFACTS_DIR)/nodejs" @tokenizer/s3
	npm install --prefix "$(ARTIFACTS_DIR)/nodejs" @aws-sdk/client-s3
