# frozen_string_literal: true

source "https://rubygems.org"

gem "nokogiri"
gem "aws-sdk-cloudwatch", "~> 1"
gem "aws-sdk-ec2", "~> 1"
gem "aws-sdk-ecs", "~> 1"
gem "aws-sdk-s3", "~> 1"
gem "net-ftp"
gem "net-sftp"

group :development do
  gem "rubocop"
end
