name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/**
      - src/**
      - test/**
      - state-machine.asl.yml
      - template.yml

concurrency:
  group: ${{ github.workflow }}

permissions:
  id-token: write
  contents: read

jobs:
  # Run a variety of linters and code style checkers.
  lint:
    uses: ./.github/workflows/lint.yml

  # Run `sam build` to create all deployable code packages, and save them all
  # as a single workflow artifact. Deploys to all environments and regions in
  # a single workflow run will use this artifact.
  build-sam:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v1
      - run: sam build --parallel
      - run: zip -rq aws-sam.zip ./.aws-sam/*
      - uses: actions/upload-artifact@v3
        with:
          name: sam-build
          path: aws-sam.zip
          retention-days: 30

  # Builds all Docker images and pushes them to ECR. Each image must be pushed
  # to ECR in every region Porter will be deployed into.
  # TODO Currently this does a separate build for each region, but could/should
  # probably just build each image once and push them to multiple regions.
  build-ftp-docker:
    needs: [lint]
    uses: ./.github/workflows/push-to-ecr.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
    with:
      src-directory: ftp # relative to src/containers
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}
  # build-ffmpeg-docker:
  #   needs: [lint]
  #   uses: ./.github/workflows/push-to-ecr.yml
  #   strategy:
  #     matrix:
  #       account-id:
  #         - "561178107736"
  #       region:
  #         - us-east-1
  #         - us-west-2
  #   with:
  #     src-directory: transcode # relative to src/containers
  #     account-id: ${{ matrix.account-id }}
  #     region: ${{ matrix.region }}

  staging-deploy:
    needs: [build-sam, build-ftp-docker]
    uses: ./.github/workflows/sam-deploy.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
    with:
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}
      ftp-image-tag: ${{ needs.build-ftp-docker.outputs.image-tag }}

  acceptance-test:
    needs: [staging-deploy]
    uses: ./.github/workflows/acceptance-test.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
        test-bucket:
          - prx-porter-sandbox
        stack-name:
          - porter-staging
    with:
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}
      test-bucket: ${{ matrix.test-bucket }}
      stack-name: ${{ matrix.stack-name }}

  production-deploy:
    needs: [acceptance-test]
    uses: ./.github/workflows/sam-deploy.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
    with:
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}
