name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/**
      - src/**
      - test/**
      - state-machine.asl.yml
      - template.yml

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    needs: [lint]
    uses: ./.github/workflows/build.yml
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
    with:
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}

  staging-deploy:
    needs: [build]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/sam-deploy.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
    with:
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}

  acceptance-test:
    needs: [staging-deploy]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/acceptance-test.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
        test-bucket:
          - prx-porter-sandbox
    with:
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}
      test-bucket: ${{ matrix.test-bucket }}

  production-deploy:
    needs: [acceptance-test]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/sam-deploy.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
    with:
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}
