name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/**
      - src/**
      - test/**
      - state-machine.asl.yml
      - template.yml

concurrency:
  group: ${{ github.workflow }}

jobs:
  lint-cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: pip3 install -r requirements.txt
      - run: cfn-lint --ignore-checks W --template template.yml
  lint-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run eslint -- "**/*.js"
      - run: npm run tsc
  lint-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
      - run: bundle install
      - run: bundle exec rubocop

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v1
      - run: sam build --parallel

  test:
    runs-on: ubuntu-latest
    needs: build
