name: Build

on:
  workflow_call:
    inputs:
      account-id:
        required: true
        type: string
      region:
        required: true
        type: string

jobs:
  # build-ffmpeg-docker:
  #   permissions:
  #     id-token: write
  #     contents: read
  #   uses: ./.github/workflows/push-to-ecr.yml
  #   strategy:
  #     matrix:
  #       account-id:
  #         - "561178107736"
  #       region:
  #         - us-east-1
  #         - us-west-2
  #   with:
  #     src-directory: transcode
  #     account-id: ${{ matrix.account-id }}
  #     region: ${{ matrix.region }}
  build-ftp-docker:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/push-to-ecr.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
    with:
      src-directory: ftp
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}
