name: SAM Deploy

on:
  workflow_call:
    inputs:
      account-id:
        required: true
        type: string
      region:
        required: true
        type: string
      ftp-image-tag:
        required: true
        type: string
      ffmpeg-image-tag:
        required: true
        type: string
      stack-name:
        required: true
        type: string

jobs:
  sam-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sam-build
      - uses: aws-actions/setup-sam@v1
      - run: unzip -q aws-sam.zip
      - run: |
          bucket_name=$(aws cloudformation describe-stacks --region ${{ inputs.region }} --stack-name aws-sam-cli-managed-default | jq -r ".Stacks[0].Outputs[0].OutputValue")
          sam deploy \
            --region ${{ inputs.region }} \
            --no-execute-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
            --stack-name ${{ inputs.stack-name }} \
            --s3-bucket "$bucket_name" \
            --capabilities CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND \
            --parameter-overrides TranscodeEcsTaskDefinitionImage="${{ inputs.ftp-image-tag }}" FtpCopyEcsTaskDefinitionImage="${{ inputs.ffmpeg-image-tag }}"
