name: Continuous Deployment

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      src-directory:
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}

jobs:
  build-ftp-docker:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/push-to-ecr.yml
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          # - us-east-1
          - us-west-2
    with:
      src-directory: ftp
      account-id: ${{ matrix.account-id }}
      region: ${{ matrix.region }}
