name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - lib/**
      - src/**
      - test/**
      - state-machine.asl.yml
      - template.yml

concurrency:
  group: ${{ github.workflow }}

jobs:
  build-ftp-docker:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        account-id:
          - "561178107736"
        region:
          - us-east-1
          - us-west-2
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ matrix.region }}
          role-to-assume: arn:aws:iam::${{ matrix.account-id }}:role/DevOps-GitHubOidcFederatedRole
          role-session-name: GitHub_Workflow-Deploy_Porter
      - run: aws ecr get-login-password --region ${{ matrix.region }} | docker login --username AWS --password-stdin ${{ matrix.account-id }}.dkr.ecr.${{ matrix.region }}.amazonaws.com
      - run: |
          sha1=`find src/containers/ftp -type f -print0 | sort -z | xargs -0 sha1sum | sha1sum | awk '{ print $1 }'`
          ecrRepositoryName="${{ github.repository }}-ftp"
          imageName="${{ matrix.account-id }}.dkr.ecr.${{ matrix.region }}.amazonaws.com/$ecrRepositoryName:$sha1"
          lookup=`aws ecr describe-images --repository-name "$ecrRepositoryName" --image-ids imageTag="$sha1" || echo "notFound"`
          if [ "$lookup" = "notFound" ]; then docker build -t ftp src/containers/ftp; fi
          if [ "$lookup" = "notFound" ]; then docker tag ftp:latest "$imageName"; fi
          # if [ "$lookup" = "notFound" ]; then docker push "$imageName"; fi
